blockExoticSubdeps: true
minimumReleaseAge: 10080
saveExact: true
shellEmulator: true
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - vite
allowBuilds:
  esbuild: true
overrides:
  vitepress>vite: npm:vite@8.0.16
